"""empty message

Revision ID: 00096fab7dc3
Revises: a2744b2a3ba1
Create Date: 2023-06-13 16:46:59.681636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00096fab7dc3'
down_revision = 'a2744b2a3ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakery_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_baked_goods_bakery_id_bakeries'), 'bakeries', ['bakery_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_baked_goods_bakery_id_bakeries'), type_='foreignkey')
        batch_op.drop_column('bakery_id')

    # ### end Alembic commands ###
