"""empty message

Revision ID: a2744b2a3ba1
Revises: 9a611fdd2f1c
Create Date: 2023-06-13 16:41:33.158086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2744b2a3ba1'
down_revision = '9a611fdd2f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.drop_constraint('fk_baked_goods_bakery_id_bakeries', type_='foreignkey')
        batch_op.drop_column('bakery_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakery_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_baked_goods_bakery_id_bakeries', 'bakeries', ['bakery_id'], ['id'])

    # ### end Alembic commands ###
